version: '3.8'
services:
    app:
        build:
            context: .
        volumes:
            - '.:/var/www'
        ports:
            - '9000:9000'
        networks:
            - laravel
        container_name: belajar-laravel-app
    nginx:
        image: 'nginx:alpine'
        ports:
            - '8000:80'
        volumes:
            - '.:/var/www'
            - './nginx:/etc/nginx/conf.d'
        depends_on:
            - app
        networks:
            - laravel
    db:
        image: 'mysql:8'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - '3307:3306'
        networks:
            - laravel
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    laravel:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
